[unix_http_server]
file=/tmp/supervisor.sock
chmod=0770
chown=root:ubuntu

[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files = /etc/supervisor/conf.d/supervisor-code-server.conf /etc/supervisor/conf.d/supervisor-openclaw.conf /etc/supervisor/conf.d/supervisor-deepseek-harness.conf /etc/supervisor/conf.d/supervisor-dashboard.conf /etc/supervisor/conf.d/supervisor-cloudflared.conf /etc/supervisor/conf.d/supervisor-analytics.conf /etc/supervisor/conf.d/supervisor-dind.conf /etc/supervisor/conf.d/supervisor-webcode-studiod.conf
