[program:webcode-studiod]
command=/opt/start-webcode-studiod.sh
directory=/home/ubuntu
user=ubuntu
environment=HOME="/home/ubuntu"
priority=230
autostart=%(ENV_ENABLE_WEBCODE_STUDIOD)s
autorestart=true
startretries=5
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/tmp/webcode_studiod_stdout.log
stderr_logfile=/tmp/webcode_studiod_stderr.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
